info:
  contact: {}
paths:
  /tags:
    post:
      consumes:
      - application/json
      description: AddTag 接口实现了添加一篇文章的功能
      parameters:
      - description: 姓名
        in: query
        name: name
        required: true
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 创建人
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
      tags:
      - example
swagger: "2.0"
